name: EnchantDeath
main: me.arasple.mc.enchantdeath.EnchantDeath

api-version: 1.13
version: ${project.version}

softdepend:
  - PlaceholderAPI

author: Arasple

commands:
  enchantdeath:
    permission: enchantdeath.admin
    permission-message: You don't have permission to do this.
