##################################################
#
# 常规事件命令设置, 支持 PlaceholderAPI
# 可配合原版、插件命令 实现自己想要的功能、无限拓展
# 例如播放音效
#
# 注意: 本配置命令基于 1.12+, 1.13+的命令有所变动
# 不能直接适配, 请自行更改
#
##################################################
# 死亡之后, 后台执行的命令
CommandsAfterDeath:
  - 'eco take {P} 100' # 扣除100金币
# 重生之后, 后台执行的命令
CommandsAfterRespawn:
  - 'effect {P} minecraft:blindness 10' # 给予致盲效果 10s
  - 'effect {P} minecraft:weakness 10' # 给予虚弱效果 10s

  #- 'effect give {P} minecraft:blindness 10' # 这两个命令和上面效果一样
  #- 'effect give {P} minecraft:weakness 10' # 用于 1.13, 1.14+

  - 'playsound minecraft:item.shield.block block {P} %player_x% %player_y% %player_z%' # 播放音效
  - 'title {P} title {"text": "&3&l重生成功, &2&l{P}!"}' # 发送 Title
  - 'title {P} subtitle {"text": "&7&l珍爱生命, 远离死亡."}' # 发送 SubTitle
# 取回死亡箱子后，后台执行的命令
CommandsAfterRetrieveDeathChest:
  - 'playsound minecraft:item.bottle.fill block {P} %player_x% %player_y% %player_z%'
  - 'title {P} title {"text": "&a&l索取成功"}' # 发送 Title
  - 'title {P} subtitle {"text": "&7&l珍爱生命, 远离死亡."}' # 发送 SubTitle

##################################################
#
# 独立世界选项
#
##################################################
Worlds:
  # 世界名称
  world:
    # 死亡后背包掉落的类型, 可选:
    #
    # KEEP = 保留背包
    # REMOVE = 全部清除
    # DEATHCHEST = 存放所有物品到一个死亡箱子
    # DROP_ALL = 全部掉落
    # DROP_RANDOM_{数量} = 随机掉落多少格子的物品 (如果玩家背包所有物品个数少于这个, 则不掉落)
    keep-inventory-type: DEATHCHEST
    # 死亡消息公告类型, 可选:
    # RANGE_{范围} = 范围; WORLD = 整个世界; SERVER = 全服; NONE = 不发送, 隐藏
    deathmessage-type: SERVER
    # 掉落的经验占玩家所有经验的比重
    # 例如设置为 0.25, 玩家本身有 1000 经验, 则掉落 250 经验, 剩余 750 经验.
    # 设置为 -1 则按原版算法
    exp-drop: 0.15
  world_nether:
    keep-inventory-type: DROP_RANDOM_5
    deathmessage-type: SERVER
    exp-drop: 0.50
  world_the_end:
    keep-inventory-type: DROP_RANDOM_10
    deathmessage-type: SERVER
    exp-drop: 0.7

##################################################
#
# 死亡箱子设置
#
# 死亡盒默认有各种保护， 无视活塞、岩浆等影响.
# 但如果你发现BUG欢迎提交
#
# 为确保公共建筑的干净整洁, 建议用 WorldGuard 设置flag
# 以保证玩家不可死亡.
#
# 所有玩家均可 Shift+右键 查看死亡盒的信息
#
##################################################
DeathChest:
  # 箱子的方块材质
  # * 设置为 pHEAD 时则为玩家本人头颅
  # * 其它则可设置为自定义方块，例如 CHEST
  type: pHEAD
  # 过期时间 (sec), 设置为 -1 则不过期
  # 强烈建议开启过期, 防止玩家恶意刷死亡盒
  expire: 600
  # 取回方式
  # * TOUCH = 交互一下
  # * BREAK = 打碎
  # * SPECIAL-MATERIAL = 特殊工具
  # * SPECIAL-LORE = 带指定LORE的工具
  retrieve: SPECIAL-MATERIAL
  # 掉落方式
  # * INV = 直接到背包，若背包已满/不足 则额外的掉在地上
  # * INV_FORCE = 必须背包足够才直接到背包
  # * DROP = 直接掉落在地上 (可被他人拾起)
  drop: INV_FORCE
  # 该项仅在 'retrieve' 设置为 'SPECIAL-MATERIAL' 时生效
  special-materials:
    - 'WOODEN_PICKAXE'
    - 'STONE_PICKAXE'
    - 'IRON_PICKAXE'
    - 'GOLDEN_PICKAXE'
    - 'DIAMOND_PICKAXE'
  # 该项仅在 'retrieve' 设置为 'SPECIAL-LORE' 时生效
  # 为方便检测你的自定义物品, Lore的彩色代码请用 §, 支持多条
  special-lores:
    - '§8特定工具: 死亡盒镐'

##################################################
#
# 自定义随机死亡消息
#
# 支持 JSON [进阶], PlaceholderAPI 变量
# 按格式自行增加, 暂时没有已经配置好的内容
#
##################################################
DeathMessages:
  # 当被未配置的实体杀死后, 是否输出控制台方便配置?
  print-unset-entity: true
  # 未被配置的死亡消息, 即显示这里的
  unknow:
    - '&8[&c☠&8] &6{P} &7死了.'
    - '&8[&c☠&8] &6{P} &7人间蒸发了.'
  causes:
    VOID:
      - '&8[&c☠&8] &6{P} &7掉入虚空了...'
      - '&8[&c☠&8] &6{P} &7被虚空吞噬了!'
      - '&8[&c☠&8] &6{P} &7掉出了这个世界.'
    FALL:
      - '&8[&c☠&8] &6{P} &7脚滑了一下'
      - '&8[&c☠&8] &6{P} &7摔死了!'
    LAVA:
      - '&8[&c☠&8] &6{P} &7在岩浆里游泳...'
      - '&8[&c☠&8] &6{P} &7被熔岩烧死了!'
    DROWNING:
      - '&8[&c☠&8] &6{P} &7溺水而亡...'
      - '&8[&c☠&8] &6{P} &7游泳失败'
  entity:
    PLAYER:
      - '&8[&c☠&8] &6{P} &7被 &b{D} &7打死了.'
    ZOMBIE:
      - '&8[&c☠&8] &6{P} &7被僵尸吃了, 坐标: %player_x%/%player_y%/%player_z%'
      - '&8[&c☠&8] &6{P} &7在跟僵尸的搏斗中不慎身亡'
      - '&8[&c☠&8] &6{P} &7打不过僵尸, 也跑不过僵尸'
    PIG_ZOMBIE:
      - '&8[&c☠&8] &6{P} &7被僵尸猪人吃了, 坐标: %player_x%/%player_y%/%player_z%'
